name: Nightly-Release

on:
  schedule:
    - cron: '0 18 * * MON-FRI' # run at 6 PM UTC, monday-friday daily
  repository_dispatch:
    types: [force-release]
  workflow_dispatch:


jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo DATE=$(date +'%Y-%m-%d') >> $GITHUB_ENV
      - uses: andelf/logseq/.github/workflows/build-desktop-release.yml@master
        with:
          tag-version: nightly-${{ env.DATE }}
          git-ref: "master"
          is-draft: true
          is-pre-release: true
          release-channel: "Nightly-${{ env.DATE }}"
